version: "3.9"
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    container_name: oracle-container
    restart: always
    ports:
      - 1522:1521
      - 5501:5500
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    environment:
      - ORACLE_SID=ecommerce
      - ORACLE_PDB=ecommerce1
      - ORACLE_PWD=Abc123456789@
      - ORACLE_CHARACTERSET=AL32UTF8
    healthcheck:
      test:
        ["CMD", "bash", "-c", "sqlplus / as sysdba <<< 'select 1 from dual'"]
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 1m

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-container
    restart: always
    depends_on:
      - oracle-db
    ports:
      - '8080:8080'

volumes:
  oracle-backup:
  oracle-data:
    driver: local
