CREATE USER C##ECOMMERCE_USER IDENTIFIED BY "Abc123456789@";

CREATE ROLE C##ECOMMERCE_DB;

GRANT CREATE SESSION, CREATE PROCEDURE TO C##ECOMMERCE_USER;

GRANT
    CREATE TABLE,
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE
TO C##ECOMMERCE_DB;

GRANT C##ECOMMERCE_DB TO C##ECOMMERCE_USER;

GRANT DBA TO C##ECOMMERCE_USER;
